# overview
name: config1
seed: 3407
output_dir: checkpoints/
report_to: wandb
wandb_project: psych-safety-finetuning

# model
model: "unsloth/Qwen3.5-35B-A3B" # # More models at https://huggingface.co/unsloth
max_seq_length: 4096
dtype: null
loss: sft
load_in_4bit: false
full_finetuning: false

# dataset
training_file: ../../00_data/train.json
val_file: ../../00_data/val.json
concatenate_datasets: false
train_on_responses_only: true
verbose_formatting: true

# training
batch_size: 4
gradient_accumulation_steps: 1
per_device_eval_batch_size: 1
warmup_steps: 175
num_train_epochs: 5
max_steps: -1
learning_rate: 1e-4 
weight_decay: 0.01
optim: "adamw_8bit"
lr_scheduler_type: "cosine"

# checkpointing
save_strategy: "epoch"
logging_steps: 1
do_eval: false
eval_strategy: "no" # "epoch"
resume_from_checkpoint: true

## lora
use_lora: true
lora_r: 1 
lora_alpha: 32 
lora_dropout: 0.0
bias: "none"
target_modules: 
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
use_gradient_checkpointing: false #"unsloth"  # True or "unsloth" for very long context
use_rslora: false
loftq_config: null
